language: node_js
node_js:
- '8'
cache: yarn
deploy:
  api_key:
    secure: by61RyU6dui876YlX+jZq2dkAHO3WToJyR+zB49hNOxlPfADtlzO2uvzthbtJDLSrUlWNtcWnnPQQ9sV5h8GCEjJMzsavzM2yKDk7FujW3S/4+qycvXN/O9kGUYOqhZamBNiNksKq/IffspFKNZ8Fqw2udP6qPq901WWOdGb2SoUncy0Mqbh0y3ElWu+1rYohgD+PhplFkGQ+hJWjObO1RmcFzQrsLftBAGRe+D+TtxsFveILO7lhJHJa8fJOFkg26Dg3xewaftmwbjtjMNaBeMsnUIV77byc9VWma3HyxiTmImgwyJeoQVSlTWV7Eq/t4JYgAELGTdJ+4f9nXYxIp2bvferIP7k2S0uRZBI2AHUtaNEncbsXP0jUEo7lzs+yiLWI8AzUh0KXC12Jbenn/StRrp1KtMGA/3hYCxL1aHQXzzudv2eEvccYM8mkJyOCXxDygBbNbKKhQpIiY5DewXiJh7hQh9cbbQ+cUqfEXhyhwEaOB+b/VXaELKFPqJATIogDnPh3omY+w8WweKAiCjWbLCr5553f7g7DV/52Z7ZyueRMpNBDjKkNm7Q6ovv1sR52ORXdgZ0Zgi0FFTQ3lBZB+QzBYWdTkgFV9WtajhQXU9Rc2OuPQ0fXTjGHNcDVUZRQhYRc6Vja4hSC54UX+1+bQgcD0b2tCvfX/9E71s=
